#!/usr/bin/env bash
set -euo pipefail

# Usage:
#   ./gen_rv32_tests.sh [OUTDIR]
#   FORCE=1 ./gen_rv32_tests.sh [OUTDIR]   # overwrite existing files
# NOTE: Does NOT generate sll/slli (already done manually).

OUTDIR="${1:-./tests}"
FORCE="${FORCE:-0}"
DATA_BASE="${DATA_BASE:-0}"

mkdir -p "$OUTDIR"

die() { echo "error: $*" >&2; exit 1; }

write_file() {
  local path="$1"
  local tmp="${path}.tmp"

  cat > "$tmp"

  if [[ -f "$path" ]] && cmp -s "$path" "$tmp"; then
    rm "$tmp"
    echo "unchanged: $path"
  else
    mv "$tmp" "$path"
    echo "updated: $path"
  fi
}

emit_autogen_banner() {
  cat <<'EOF'
// AUTO-GENERATED FILE — DO NOT EDIT BY HAND
// Generated by gen_rv32_tests.sh
// Christian LamAlvarez
// clamalvarez@hmc.edu
// 2/11/2026

EOF
}

emit_header() {
  local testname="$1"  # e.g. srl
  emit_autogen_banner
  cat <<EOF
.extern return_${testname}_test
.extern fail

.section .text.init
.globl ${testname}_test
.type  ${testname}_test, @function

${testname}_test:
EOF
}

emit_set_gp_code() {
  local code="$1"

  if [[ "$code" -ge -2048 && "$code" -le 2047 ]]; then
    cat <<EOF
    addi gp, x0, ${code}
EOF
    return
  fi

  local base=2047
  local rem=$((code - base))

  # For your use (<= ~2600), this always fits imm12.
  cat <<EOF
    addi gp, x0, ${base}
    addi gp, gp, ${rem}
EOF
}

emit_fail_footer() {
  local upper="$1"
  local base_gp="$2"
  for i in $(seq 1 10); do
    local code=$((base_gp + i))
    cat <<EOF

Fail_${upper}_${i}:
$(emit_set_gp_code "$code")
    jal  x0, fail
EOF
  done
}

# EXPECTED RESULT FUNCTIONS
# -----------------------------
# EXPECTED RESULT: SHIFTS (RV32)
# Supported ops: sll/slli/srl/srli/sra/srai
# Returns: "<signed_expected> <hex_u32>"
# -----------------------------
rv32_expect_shift() {
  # args: OP RS1 SHAMT
  python3 - "$1" "$2" "$3" <<'PY'
import sys

op = sys.argv[1]
rs1 = int(sys.argv[2], 0)
shamt_in = int(sys.argv[3], 0)

def to_u32(x):
    return x & 0xFFFFFFFF

def to_s32(u):
    u &= 0xFFFFFFFF
    return u if u < 0x80000000 else u - 0x100000000

shamt = shamt_in & 0x1F  # RV32 uses low 5 bits
u = to_u32(rs1)

if op in ("sll", "slli"):
    res_u = to_u32(u << shamt)
elif op in ("srl", "srli"):
    res_u = (u >> shamt)  # logical shift right
elif op in ("sra", "srai"):
    s = to_s32(u)          # arithmetic shift right
    res_u = to_u32(s >> shamt)
else:
    raise SystemExit(f"unsupported shift op: {op}")

res_s = to_s32(res_u)
print(res_s, f"0x{res_u:08x}")
PY
}

# ----------------------------------------
# EXPECTED RESULT: UNSIGNED COMPARES (RV32)
# Supported ops: sltu, sltiu
# sltu:  unsigned(rs1) < unsigned(rs2)
# sltiu: unsigned(rs1) < unsigned(signext(imm12))
# Returns: "0" or "1"
# ----------------------------------------
rv32_expect_ucmp() {
  # args: OP RS1 RHS   (RHS is RS2 for sltu, IMM12 for sltiu)
  python3 - "$1" "$2" "$3" <<'PY'
import sys

op = sys.argv[1]
rs1 = int(sys.argv[2], 0)
rhs = int(sys.argv[3], 0)

def to_u32(x):
    return x & 0xFFFFFFFF

def signext_imm12(x):
    x &= 0xFFF
    return x if x < 0x800 else x - 0x1000

a = to_u32(rs1)

if op == "sltu":
    b = to_u32(rhs)
elif op == "sltiu":
    b = to_u32(signext_imm12(rhs))
else:
    raise SystemExit(f"unsupported ucmp op: {op}")

print(1 if a < b else 0)
PY
}

fits_imm12() {
  local x="$1"
  [[ "$x" -ge -2048 && "$x" -le 2047 ]]
}

# ----------------------------------------
# EXPECTED RESULT: LOADS (RV32, little-endian)
# Supported ops: lb, lbu, lh, lhu
# Memory is provided as hex bytes: e.g. "00 ff 7f 80 ..."
# offset is a byte offset into that byte array
# Returns: "<signed_expected> <hex_u32>"
# ----------------------------------------
rv32_expect_load() {
  # args: OP "HEX_BYTES" OFFSET
  python3 - "$1" "$2" "$3" <<'PY'
import sys

op = sys.argv[1]
hex_bytes = sys.argv[2]
off = int(sys.argv[3])

# parse bytes like: "00 ff 7f 80"
mem = bytes(int(b, 16) for b in hex_bytes.split())

def to_u32(x): return x & 0xFFFFFFFF
def to_s32(u):
    u &= 0xFFFFFFFF
    return u if u < 0x80000000 else u - 0x100000000

def signext(val, bits):
    sign = 1 << (bits - 1)
    mask = (1 << bits) - 1
    val &= mask
    return val - (1 << bits) if (val & sign) else val

if op in ("lb", "lbu"):
    b = mem[off]
    if op == "lb":
        v = signext(b, 8)
    else:
        v = b
elif op in ("lh", "lhu"):
    # little-endian halfword
    b0 = mem[off]
    b1 = mem[off + 1]
    hw = b0 | (b1 << 8)
    if op == "lh":
        v = signext(hw, 16)
    else:
        v = hw
else:
    raise SystemExit(f"unsupported load op: {op}")

res_u = to_u32(v)
print(to_s32(res_u), f"0x{res_u:08x}")
PY
}

# ----------------------------------------
# EXPECTED RESULT: STORES (RV32, little-endian)
# Supported ops: sb, sh
# Given an initial 32-bit word (4 bytes) as hex bytes, applies the store at byte offset,
# and returns expected full 32-bit word after the store:
# Returns: "<signed_expected> <hex_u32>"
# ----------------------------------------
rv32_expect_store_word() {
  # args: OP "WORD_HEX_BYTES" BYTE_OFFSET STORE_VAL
  # WORD_HEX_BYTES example: "aa bb cc dd" (4 bytes, little-endian in memory)
  python3 - "$1" "$2" "$3" "$4" <<'PY'
import sys

op = sys.argv[1]
word_hex = sys.argv[2]
byte_off = int(sys.argv[3])
store_val = int(sys.argv[4])

bs = [int(b,16) for b in word_hex.split()]
if len(bs) != 4:
    raise SystemExit("WORD_HEX_BYTES must be exactly 4 bytes")

def to_u32(x): return x & 0xFFFFFFFF
def to_s32(u):
    u &= 0xFFFFFFFF
    return u if u < 0x80000000 else u - 0x100000000

# apply store into the 4-byte array
if op == "sb":
    bs[byte_off] = store_val & 0xFF
elif op == "sh":
    # writes 2 bytes little-endian; expect byte_off 0 or 2 (aligned halfword in word)
    bs[byte_off]     = store_val & 0xFF
    bs[byte_off + 1] = (store_val >> 8) & 0xFF
else:
    raise SystemExit(f"unsupported store op: {op}")

u = bs[0] | (bs[1]<<8) | (bs[2]<<16) | (bs[3]<<24)
print(to_s32(u), f"0x{u:08x}")
PY
}

# ----------------------------------------
# EXPECTED RESULT: BRANCHES (RV32)
# Supported ops: bne, blt, bltu, bge, bgeu
# Returns: "0" (not taken) or "1" (taken)
# ----------------------------------------
rv32_expect_branch() {
  # args: OP RS1 RS2
  python3 - "$1" "$2" "$3" <<'PY'
import sys

op = sys.argv[1]
rs1 = int(sys.argv[2], 0)
rs2 = int(sys.argv[3], 0)

def to_u32(x): return x & 0xFFFFFFFF
def to_s32(u):
    u &= 0xFFFFFFFF
    return u if u < 0x80000000 else u - 0x100000000

a_u = to_u32(rs1)
b_u = to_u32(rs2)
a_s = to_s32(a_u)
b_s = to_s32(b_u)

take = 0
if op == "bne":
    take = 1 if a_u != b_u else 0
elif op == "blt":
    take = 1 if a_s < b_s else 0
elif op == "bltu":
    take = 1 if a_u < b_u else 0
elif op == "bge":
    take = 1 if a_s >= b_s else 0
elif op == "bgeu":
    take = 1 if a_u >= b_u else 0
else:
    raise SystemExit(f"unsupported branch op: {op}")

print(take)
PY
}

# ----------------------------------------
# EXPECTED RESULT: U-TYPE UPPER (RV32)
# Used for: lui, auipc (imm20 << 12)
# Accepts signed/unsigned imm in assembly form; masks to 20 bits.
# Returns: "<signed_expected> <hex_u32>"
# ----------------------------------------
rv32_expect_u_upper() {
  # args: IMM20
  python3 - "$1" <<'PY'
import sys
imm = int(sys.argv[1], 0)

def to_u32(x): return x & 0xFFFFFFFF
def to_s32(u):
    u &= 0xFFFFFFFF
    return u if u < 0x80000000 else u - 0x100000000

imm20 = imm & 0xFFFFF
u = to_u32(imm20 << 12)
print(to_s32(u), f"0x{u:08x}")
PY
}

# Global literal pool accumulator for the current file
LIT_POOL=""

# EMITTING TEST BLOCKS AND GEN_FILE FUNCTIONS

emit_load_expected_into_t3() {
  local exp_s="$1"
  local exp_hex="$2"

  if fits_imm12 "$exp_s"; then
    cat <<EOF
        addi t3, x0, $exp_s
EOF
  else
    local u=$(( exp_s & 0xffffffff ))
    local hi=$(( (u + 0x800) >> 12 ))
    local lo=$(( u - (hi << 12) ))

    # HARD GUARANTEE lo fits imm12
    if ! fits_imm12 "$lo"; then
      echo "FATAL: lo out of range in emit_load_expected_into_t3: $lo" >&2
      exit 1
    fi

    cat <<EOF
        lui  t3, $hi
        addi t3, t3, $lo
EOF
  fi
}

# Load an arbitrary 32-bit signed constant into rd using only:
#   addi (if fits imm12) OR jal+addi+lw from literal pool.
# Uses the same LIT_POOL mechanism as expected-value loading.
emit_load_const() {
  local rd="$1"
  local val="$2"

  read -r val_s val_hex < <(python3 - "$val" <<'PY'
import sys
x = int(sys.argv[1], 0)
u = x & 0xFFFFFFFF
s = u if u < 0x80000000 else u - 0x100000000
print(s, f"0x{u:08x}")
PY
)

  if fits_imm12 "$val_s"; then
    cat <<EOF
        addi ${rd}, x0, ${val_s}
EOF
  else
    local u=$(( val_s & 0xffffffff ))
    local hi=$(( (u + 0x800) >> 12 ))
    local lo=$(( u - (hi << 12) ))

    # HARD GUARANTEE lo fits imm12
    if ! fits_imm12 "$lo"; then
      echo "FATAL: lo out of range in emit_load_const: $lo" >&2
      exit 1
    fi

    cat <<EOF
        lui  ${rd}, $hi
        addi ${rd}, ${rd}, $lo
EOF
  fi
}

emit_test_block_shift_rtype() {
  local op="$1" upper="$2" i="$3" rs1="$4" shamt="$5" next="$6"
  read -r exp_s exp_hex < <(rv32_expect_shift "$op" "$rs1" "$shamt")

  cat <<EOF
    test${i}:
EOF
  emit_load_const t0 "${rs1}" "${upper}" "$i"
  emit_load_const t1 "${shamt}" "${upper}" "$i"
  cat <<EOF
        ${op}  t2, t0, t1
EOF

  emit_load_expected_into_t3 "$exp_s" "$exp_hex" "${upper}" "$i"

  cat <<EOF
        beq  t2, t3, ${next}
        jal  x0, Fail_${upper}_${i}

EOF
}

emit_test_block_shift_itype() {
  local op="$1" upper="$2" i="$3" rs1="$4" shamt="$5" next="$6"
  read -r exp_s exp_hex < <(rv32_expect_shift "$op" "$rs1" "$shamt")

  cat <<EOF
    test${i}:
EOF
  emit_load_const t0 "${rs1}" "${upper}" "$i"
  cat <<EOF
        ${op} t2, t0, ${shamt}
EOF

  emit_load_expected_into_t3 "$exp_s" "$exp_hex" "${upper}" "$i"

  cat <<EOF
        beq  t2, t3, ${next}
        jal  x0, Fail_${upper}_${i}

EOF
}

# Load address of a label into a register using only jal+addi (RV32I-safe).
# Usage: emit_load_addr t4 test_mem
emit_load_addr() {
  local rd="$1"
  local addr="$2"

  local u=$((addr & 0xffffffff))
  local hi=$(((u + 0x800) >> 12))
  local lo=$((u - (hi << 12)))

  cat <<EOF
        lui  ${rd}, ${hi}
        addi ${rd}, ${rd}, ${lo}
EOF
}

emit_test_block_load() {
  local op="$1" upper="$2" i="$3" base_addr="$4" hex_bytes="$5" off="$6" next="$7"

  read -r exp_s exp_hex < <(rv32_expect_load "$op" "$hex_bytes" "$off")

  cat <<EOF
    test${i}:
        jal   t4, 1f
    0:
        .byte ${hex_bytes// /, 0x}
    1:
        # t4 = address of label 0 (PC+4 from jal)

        addi  t0, t4, ${off}
        ${op}  t2, 0(t0)
EOF

  emit_load_expected_into_t3 "$exp_s" "$exp_hex"

  cat <<EOF
        beq  t2, t3, ${next}
        jal  x0, Fail_${upper}_${i}

EOF
}

emit_test_block_store_word() {
  # args: OP UPPER i BASE_ADDR_UNUSED WORD_HEX BYTE_OFF STORE_VAL next
  local op="$1" upper="$2" i="$3" _base="$4" word_hex="$5" boff="$6" sval="$7" next="$8"

  # parse initial bytes (memory order)
  local b0 b1 b2 b3
  read -r b0 b1 b2 b3 <<<"$word_hex"

  # compute expected bytes after store (in bash)
  local eb0="$b0" eb1="$b1" eb2="$b2" eb3="$b3"

  if [[ "$op" == "sb" ]]; then
    local v=$((sval & 0xFF))
    local vhex; printf -v vhex "%02x" "$v"
    case "$boff" in
      0) eb0="$vhex" ;;
      1) eb1="$vhex" ;;
      2) eb2="$vhex" ;;
      3) eb3="$vhex" ;;
      *) echo "bad boff sb: $boff" >&2; exit 1 ;;
    esac
  else # sh
    local vlo=$((sval & 0xFF))
    local vhi=$(((sval >> 8) & 0xFF))
    local vlohex vhihex
    printf -v vlohex "%02x" "$vlo"
    printf -v vhihex "%02x" "$vhi"
    case "$boff" in
      0) eb0="$vlohex"; eb1="$vhihex" ;;
      2) eb2="$vlohex"; eb3="$vhihex" ;;
      *) echo "bad boff sh: $boff" >&2; exit 1 ;;
    esac
  fi

  # store value bytes for scratch->lw
  local sv0=$((sval & 0xFF))
  local sv1=$(((sval >> 8) & 0xFF))

  cat <<EOF
    test${i}:
        addi sp, sp, -12
        addi t0, sp, 0      # target word   @ sp+0
        addi t2, sp, 4      # expected word @ sp+4
        addi t3, sp, 8      # scratch       @ sp+8

        # init target bytes
        addi t1, x0, 0x${b0}; sb t1, 0(t0)
        addi t1, x0, 0x${b1}; sb t1, 1(t0)
        addi t1, x0, 0x${b2}; sb t1, 2(t0)
        addi t1, x0, 0x${b3}; sb t1, 3(t0)

        # init expected bytes
        addi t1, x0, 0x${eb0}; sb t1, 0(t2)
        addi t1, x0, 0x${eb1}; sb t1, 1(t2)
        addi t1, x0, 0x${eb2}; sb t1, 2(t2)
        addi t1, x0, 0x${eb3}; sb t1, 3(t2)

        # build store value in t1 via scratch bytes then lw
        addi t1, x0, ${sv0}; sb t1, 0(t3)
        addi t1, x0, ${sv1}; sb t1, 1(t3)
        addi t1, x0, 0;      sb t1, 2(t3)
        addi t1, x0, 0;      sb t1, 3(t3)
        lw   t1, 0(t3)

        # perform store into target
        ${op} t1, ${boff}(t0)

        # compare lw(target) vs lw(expected)
        lw   t4, 0(t0)
        lw   t5, 0(t2)
        beq  t4, t5, 1f
        jal  x0, Fail_${upper}_${i}
1:
        addi sp, sp, 12
        jal  x0, ${next}

EOF
}

emit_test_block_branch() {
  local op="$1" upper="$2" i="$3" rs1="$4" rs2="$5" next="$6"
  local exp
  exp="$(rv32_expect_branch "$op" "$rs1" "$rs2")"

  cat <<EOF
    test${i}:
EOF
  emit_load_const t0 "${rs1}" "${upper}" "$i"
  emit_load_const t1 "${rs2}" "${upper}" "$i"
  cat <<EOF
        addi t2, x0, 0
        ${op}  t0, t1, ${upper}_TAKEN_${i}
        jal  x0, ${upper}_AFTER_${i}
${upper}_TAKEN_${i}:
        addi t2, x0, 1
${upper}_AFTER_${i}:
        addi t3, x0, ${exp}
        beq  t2, t3, ${next}
        jal  x0, Fail_${upper}_${i}

EOF
}

emit_test_block_sltu() {
  local upper="$1" i="$2" rs1="$3" rs2="$4" next="$5"
  local exp
  exp="$(rv32_expect_ucmp "sltu" "$rs1" "$rs2")"

  cat <<EOF
    test${i}:
EOF
  emit_load_const t0 "${rs1}" "${upper}" "$i"
  emit_load_const t1 "${rs2}" "${upper}" "$i"
  cat <<EOF
        sltu t2, t0, t1
        addi t3, x0, ${exp}
        beq  t2, t3, ${next}
        jal  x0, Fail_${upper}_${i}

EOF
}

emit_test_block_sltiu() {
  local upper="$1" i="$2" rs1="$3" imm="$4" next="$5"
  local exp
  exp="$(rv32_expect_ucmp "sltiu" "$rs1" "$imm")"

  cat <<EOF
    test${i}:
EOF
  emit_load_const t0 "${rs1}" "${upper}" "$i"
  cat <<EOF
        sltiu t2, t0, ${imm}
        addi  t3, x0, ${exp}
        beq   t2, t3, ${next}
        jal   x0, Fail_${upper}_${i}

EOF
}

emit_test_block_jalr() {
  # args: UPPER i next_label
  local upper="$1" i="$2" next="$3"

  cat <<EOF
    test${i}:
        addi t3, x0, 0          # flag = 0

        # --- Get address of TARGET into t0 without AUIPC/LUI ---
        jal  t0, ${upper}_GET_TGT_${i}
${upper}_GET_TGT_${i}:
        # t0 = PC+4 of the jal above (i.e., address of the next instruction)
        # Now redirect control flow away so we can place TARGET elsewhere.
        jal  x0, ${upper}_DO_JALR_${i}

        # --- This label's address is what we want to jump to ---
${upper}_TARGET_${i}:
        addi t3, x0, 1          # flag = 1 (means we landed)
        jal  x0, ${upper}_CHECK_${i}

${upper}_DO_JALR_${i}:
        # At this point, t0 holds address of the instruction right after the jal to GET_TGT.
        # That instruction is the 'jal x0, DO_JALR' itself, NOT TARGET.
        # So instead, do another jal that *lands near TARGET* and captures its link.

        jal  t0, ${upper}_TGT_LINK_${i}
${upper}_TGT_LINK_${i}:
        # t0 = PC+4 here, and we are positioned immediately before TARGET via fall-through.
        # Place TARGET immediately next so t0 == address of TARGET.
        jal  x0, ${upper}_TARGET_${i}

        # (control never reaches here)

${upper}_CHECK_${i}:
        # flag must be 1
        addi t4, x0, 1
        beq  t3, t4, ${next}
        jal  x0, Fail_${upper}_${i}

EOF
}

emit_test_block_lui() {
  # args: UPPER i imm20 next_label
  local upper="$1" i="$2" imm="$3" next="$4"
  read -r exp_s exp_hex < <(rv32_expect_u_upper "$imm")

  cat <<EOF
    test${i}:
        lui  t2, ${imm}
EOF
  emit_load_expected_into_t3 "$exp_s" "$exp_hex" "${upper}" "$i"
  cat <<EOF
        beq  t2, t3, ${next}
        jal  x0, Fail_${upper}_${i}

EOF
}

emit_test_block_auipc() {
  # args: UPPER i imm20 next_label
  local upper="$1" i="$2" imm="$3" next="$4"

  # upper = imm<<12 (constant)
  read -r up_s up_hex < <(rv32_expect_u_upper "$imm")

  cat <<EOF
    test${i}:
        auipc t2, ${imm}
        jal   t0, ${upper}_AUPC_${i}
${upper}_AUPC_${i}:
        addi  t0, t0, -8          # t0 = PC(auipc)
EOF

  # load (imm<<12) into t3 (literal pool if needed)
  emit_load_expected_into_t3 "$up_s" "$up_hex" "${upper}" "$i"

  cat <<EOF
        add   t3, t3, t0          # t3 = PC(auipc) + (imm<<12)
        beq   t2, t3, ${next}
        jal   x0, Fail_${upper}_${i}

EOF
}

gen_lui_file() {
  # args: name upper base_gp vectors_array_name
  local name="$1" upper="$2" base_gp="$3" vectors_name="$4"
  LIT_POOL=""
  local -n VEC="$vectors_name"

  emit_header "$name"

  local i=1
  for imm in "${VEC[@]}"; do
    local next="test$((i+1))"; [[ "$i" -eq 10 ]] && next="pass"
    emit_test_block_lui "$upper" "$i" "$imm" "$next"
    i=$((i+1))
  done

  cat <<EOF
    pass:
        jal  x0, return_${name}_test
EOF

  if [[ -n "$LIT_POOL" ]]; then
    cat <<EOF

    # ---- literal pool (auto-generated) ----
$LIT_POOL
EOF
  fi

  emit_fail_footer "$upper" "$base_gp"
}

gen_auipc_file() {
  # args: name upper base_gp vectors_array_name
  local name="$1" upper="$2" base_gp="$3" vectors_name="$4"
  LIT_POOL=""
  local -n VEC="$vectors_name"

  emit_header "$name"

  local i=1
  for imm in "${VEC[@]}"; do
    local next="test$((i+1))"; [[ "$i" -eq 10 ]] && next="pass"
    emit_test_block_auipc "$upper" "$i" "$imm" "$next"
    i=$((i+1))
  done

  cat <<EOF
    pass:
        jal  x0, return_${name}_test
EOF

  if [[ -n "$LIT_POOL" ]]; then
    cat <<EOF

    # ---- literal pool (auto-generated) ----
$LIT_POOL
EOF
  fi

  emit_fail_footer "$upper" "$base_gp"
}

gen_store_file() {
  # args: OP UPPER BASE_GP VECTORS_NAME
  local op="$1" upper="$2" base_gp="$3" vectors_name="$4"
  LIT_POOL=""
  local -n VEC="$vectors_name"

  emit_header "$op"

  local i=1
  for v in "${VEC[@]}"; do
    IFS='|' read -r _ whex boff sval <<<"$v"
    local next="test$((i+1))"
    [[ "$i" -eq 10 ]] && next="pass"

    emit_test_block_store_word "$op" "$upper" "$i" 4352 "$whex" "$boff" "$sval" "$next"

    i=$((i+1))
  done

  cat <<EOF
    pass:
        jal  x0, return_${op}_test
EOF

  emit_fail_footer "$upper" "$base_gp"

  cat <<EOF

.section .data
.org 0x1100
.align 2
EOF

  local i2=1
  for v in "${VEC[@]}"; do
    IFS='|' read -r _ whex _ _ <<<"$v"
    cat <<EOF
store_word_${i2}:
    .byte $(echo "$whex" | sed 's/ /, 0x/g; s/^/0x/')
EOF
    i2=$((i2+1))
  done
}

gen_load_file() {
  local op="$1" upper="$2" base_gp="$3" vectors_name="$4" mem_label="$5" hex_bytes="$6"
  LIT_POOL=""
  local -n VEC="$vectors_name"

  emit_header "$op"

  local i=1
  for off in "${VEC[@]}"; do
    local next="test$((i+1))"
    [[ "$i" -eq 10 ]] && next="pass"
    emit_test_block_load "$op" "$upper" "$i" 0 "$hex_bytes" "$off" "$next"
    i=$((i+1))
  done

  cat <<EOF
    pass:
        jal  x0, return_${op}_test
EOF

  emit_fail_footer "$upper" "$base_gp"
}

gen_shift_rtype_file() {
  # args: name upper base_gp vectors_array_name
  local name="$1"         # srl / sra
  local upper="$2"        # SRL / SRA
  local base_gp="$3"      # 700 / 900
  local vectors_name="$4"

  LIT_POOL=""
  local -n VEC="$vectors_name"

  emit_header "$name"

  local i=1
  for vec in "${VEC[@]}"; do
    read -r rs1 shamt <<<"$vec"
    local next="test$((i+1))"
    [[ "$i" -eq 10 ]] && next="pass"
    emit_test_block_shift_rtype "$name" "$upper" "$i" "$rs1" "$shamt" "$next"
    i=$((i+1))
  done

  cat <<EOF
    pass:
        jal  x0, return_${name}_test
EOF

  if [[ -n "$LIT_POOL" ]]; then
    cat <<EOF

    # ---- literal pool (auto-generated) ----
$LIT_POOL
EOF
  fi

  emit_fail_footer "$upper" "$base_gp"
}

gen_shift_itype_file() {
  # args: name upper base_gp vectors_array_name
  local name="$1"         # srli / srai
  local upper="$2"        # SRLI / SRAI
  local base_gp="$3"      # 800 / 1000
  local vectors_name="$4"

  LIT_POOL=""
  local -n VEC="$vectors_name"

  emit_header "$name"

  local i=1
  for vec in "${VEC[@]}"; do
    read -r rs1 shamt <<<"$vec"
    local next="test$((i+1))"
    [[ "$i" -eq 10 ]] && next="pass"
    emit_test_block_shift_itype "$name" "$upper" "$i" "$rs1" "$shamt" "$next"
    i=$((i+1))
  done

  cat <<EOF
    pass:
        jal  x0, return_${name}_test
EOF

  if [[ -n "$LIT_POOL" ]]; then
    cat <<EOF

    # ---- literal pool (auto-generated) ----
$LIT_POOL
EOF
  fi

  emit_fail_footer "$upper" "$base_gp"
}

gen_branch_file() {
  # args: name upper base_gp vectors_array_name
  local name="$1" upper="$2" base_gp="$3" vectors_name="$4"
  local -n VEC="$vectors_name"

  LIT_POOL=""

  emit_header "$name"

  local i=1
  for vec in "${VEC[@]}"; do
    read -r rs1 rs2 <<<"$vec"
    local next="test$((i+1))"; [[ "$i" -eq 10 ]] && next="pass"
    emit_test_block_branch "$name" "$upper" "$i" "$rs1" "$rs2" "$next"
    i=$((i+1))
  done

  cat <<EOF
    pass:
        jal  x0, return_${name}_test
EOF

  if [[ -n "$LIT_POOL" ]]; then
    cat <<EOF

    # ---- literal pool (auto-generated) ----
$LIT_POOL
EOF
  fi

  emit_fail_footer "$upper" "$base_gp"
}

gen_sltu_file() {
  local name="$1" upper="$2" base_gp="$3" vectors_name="$4"
  local -n VEC="$vectors_name"

  LIT_POOL=""   # ADD

  emit_header "$name"

  local i=1
  for vec in "${VEC[@]}"; do
    read -r rs1 rs2 <<<"$vec"
    local next="test$((i+1))"; [[ "$i" -eq 10 ]] && next="pass"
    emit_test_block_sltu "$upper" "$i" "$rs1" "$rs2" "$next"
    i=$((i+1))
  done

  cat <<EOF
    pass:
        jal  x0, return_${name}_test
EOF

  # ADD
  if [[ -n "$LIT_POOL" ]]; then
    cat <<EOF

    # ---- literal pool (auto-generated) ----
$LIT_POOL
EOF
  fi

  emit_fail_footer "$upper" "$base_gp"
}

gen_sltiu_file() {
  local name="$1" upper="$2" base_gp="$3" vectors_name="$4"
  local -n VEC="$vectors_name"

  LIT_POOL=""   # ADD

  emit_header "$name"

  local i=1
  for vec in "${VEC[@]}"; do
    read -r rs1 imm <<<"$vec"
    local next="test$((i+1))"; [[ "$i" -eq 10 ]] && next="pass"
    emit_test_block_sltiu "$upper" "$i" "$rs1" "$imm" "$next"
    i=$((i+1))
  done

  cat <<EOF
    pass:
        jal  x0, return_${name}_test
EOF

  # ADD
  if [[ -n "$LIT_POOL" ]]; then
    cat <<EOF

    # ---- literal pool (auto-generated) ----
$LIT_POOL
EOF
  fi

  emit_fail_footer "$upper" "$base_gp"
}

gen_jalr_file() {
  local base_gp="$1"
  local name="jalr" upper="JALR"

  emit_header "$name"

  local i
  for i in $(seq 1 10); do
    local next="test$((i+1))"
    [[ "$i" -eq 10 ]] && next="pass"
    emit_test_block_jalr "$upper" "$i" "$next"
  done

  cat <<EOF
    pass:
        jal  x0, return_${name}_test
EOF

  emit_fail_footer "$upper" "$base_gp"
}

# -----------------------------
# Input vectors (inputs only!)
# Each entry: "rs1 shamt"
# Script computes expected RV32 result automatically.
# Include shamt-masking edge cases: 32->0, 33->1, 63->31, etc.
# -----------------------------

SRL_INPUTS=(
  "8 1"             # 8 >> 1 = 4
  "7 2"             # 7 >> 2 = 1
  "-1 1"            # 0xFFFFFFFF >> 1 = 0x7FFFFFFF
  "-2147483648 1"   # 0x80000000 >> 1 = 0x40000000
  "1 0"             # shift by 0
  "1024 5"          # 1024 >> 5 = 32
  "1 31"            # 1 >> 31 = 0
  "-2 1"            # 0xFFFFFFFE >> 1 = 0x7FFFFFFF
  "1 32"            # masked shamt (32->0)
  "1 33"            # masked shamt (33->1)
)

SRLI_INPUTS=(
  "8 1"
  "7 2"
  "-1 1"
  "-2147483648 1"
  "1 0"
  "1024 5"
  "1 31"
  "-2 1"
  "2147483647 30"
  "-2147483648 30"
)

SRA_INPUTS=(
  "-1 1"            # stays -1 with arithmetic shift
  "-2 1"            # -2 >> 1 = -1 (arithmetic)
  "-2147483648 1"   # 0x80000000 >> 1 = 0xC0000000 (sign-extend)
  "-2147483648 31"  # >>31 = -1
  "2147483647 1"    # 0x7FFFFFFF >> 1 = 0x3FFFFFFF
  "16 3"            # 16 >> 3 = 2
  "-16 3"           # -16 >> 3 = -2
  "1 0"             # shift by 0
  "-1 32"           # masked shamt (32->0) => -1
  "-8 33"           # masked shamt (33->1) => -4
)

SRAI_INPUTS=(
  "-1 1"
  "-2 1"
  "-2147483648 1"
  "-2147483648 31"
  "2147483647 1"
  "16 3"
  "-16 3"
  "1 0"
  "-1 30"
  "-8 30"
)

# Use small signed immediates but hit unsigned edge behavior (0 vs -1, etc).
SLTU_INPUTS=(
  "0 0"           # 0 < 0  => 0
  "0 1"           # 0 < 1  => 1
  "1 0"           # 1 < 0  => 0
  "-1 0"          # 0xFFFFFFFF < 0 => 0
  "0 -1"          # 0 < 0xFFFFFFFF => 1
  "-1 -1"         # equal => 0
  "-2147483648 0" # 0x80000000 < 0 => 0
  "0 -2147483648" # 0 < 0x80000000 => 1
  "2147483647 -1" # 0x7FFFFFFF < 0xFFFFFFFF => 1
  "-1 2147483647" # 0xFFFFFFFF < 0x7FFFFFFF => 0
)

# For sltiu, the immediate is IMM12 (signed 12-bit in encoding).
# Keep imm within [-2048, 2047] to stay legal.
SLTIU_INPUTS=(
  "0 0"       # 0 < 0 => 0
  "0 1"       # 0 < 1 => 1
  "1 0"       # 1 < 0 => 0
  "0 -1"      # imm=-1 signext->0xFFFFFFFF, so 0 < 0xFFFFFFFF => 1
  "-1 -1"     # 0xFFFFFFFF < 0xFFFFFFFF => 0
  "-1 0"      # 0xFFFFFFFF < 0 => 0
  "2047 2047" # equal => 0
  "2046 2047" # 2046 < 2047 => 1
  "0 -2048"   # 0 < 0xFFFFF800 => 1 (unsigned)
  "-2048 -2048" # equal => 0
)

LOAD_MEM_HEX="00 01 7f 80 ff 10 f0 aa 55 33 cc 12 34 00 80 ff"

LB_OFFSETS=(0 1 2 3 4 5 6 7 8 9)
LBU_OFFSETS=(0 1 2 3 4 5 6 7 8 9)
LH_OFFSETS=(0 2 4 6 8 10 12 14 0 2)      # aligned
LHU_OFFSETS=(0 2 4 6 8 10 12 14 0 2)

SB_VECTORS=(
  "sb_w0|aa bb cc dd|0|0"
  "sb_w1|aa bb cc dd|1|255"
  "sb_w2|00 00 00 00|2|127"
  "sb_w3|00 00 00 00|3|128"
  "sb_w4|12 34 56 78|0|171"
  "sb_w5|12 34 56 78|1|205"
  "sb_w6|ff ff ff ff|2|0"
  "sb_w7|ff 00 ff 00|3|1"
  "sb_w8|01 02 03 04|2|16"
  "sb_w9|10 20 30 40|1|240"
)

SH_VECTORS=(
  "sh_w0|aa bb cc dd|0|0"
  "sh_w1|aa bb cc dd|0|65535"     # lower 16 bits written (0xFFFF)
  "sh_w2|00 00 00 00|2|4660"      # 0x1234 at offset 2
  "sh_w3|ff ff ff ff|0|32768"     # 0x8000
  "sh_w4|12 34 56 78|2|1"
  "sh_w5|12 34 56 78|0|43981"     # 0xABCD
  "sh_w6|01 02 03 04|2|65535"
  "sh_w7|10 20 30 40|0|16"
  "sh_w8|00 80 00 80|2|0"
  "sh_w9|00 01 00 02|0|2"
)

BNE_INPUTS=(
  "0 0"
  "0 1"
  "1 0"
  "-1 -1"
  "-1 0"
  "0 -1"
  "-2147483648 2147483647"
  "2147483647 -2147483648"
  "123 123"
  "-2048 2047"
)

BLT_INPUTS=(
  "0 0"
  "-1 0"
  "0 -1"
  "-2 -1"
  "-2147483648 0"
  "0 2147483647"
  "2147483647 -2147483648"
  "5 10"
  "10 5"
  "-2048 -2047"
)

BLTU_INPUTS=(
  "0 0"
  "0 1"
  "1 0"
  "-1 0"              # 0xFFFFFFFF < 0 ? no
  "0 -1"              # 0 < 0xFFFFFFFF ? yes
  "-2147483648 0"     # 0x80000000 < 0 ? no
  "0 -2147483648"     # 0 < 0x80000000 ? yes
  "2147483647 -1"     # 0x7FFFFFFF < 0xFFFFFFFF ? yes
  "-1 2147483647"     # no
  "5 10"
)

BGE_INPUTS=(
  "0 0"
  "0 -1"
  "-1 0"
  "-1 -1"
  "10 5"
  "5 10"
  "-2147483648 0"
  "2147483647 -2147483648"
  "-2047 -2048"
  "-2048 2047"
)

BGEU_INPUTS=(
  "0 0"
  "1 0"
  "0 1"
  "-1 0"              # yes (0xFFFFFFFF >= 0)
  "0 -1"              # no
  "-2147483648 0"     # yes (0x80000000 >= 0)
  "0 -2147483648"     # no
  "2147483647 -1"     # no
  "-1 2147483647"     # yes
  "10 5"
)

LUI_IMM20S=(0 1 2 7 0x12345 0x7ffff 0x80000 0xfffff 0xffffe 0xff000)
AUIPC_IMM20S=(0 1 2 7 0x12345 0x7ffff 0x80000 0xfffff 0xffffe 0xff000)

main() {
  # NOTE: sll/slli intentionally not generated here.

  write_file "$OUTDIR/srl_test.S" <<EOF
$(gen_shift_rtype_file "srl" "SRL" 700 SRL_INPUTS)
EOF

  write_file "$OUTDIR/srli_test.S" <<EOF
$(gen_shift_itype_file "srli" "SRLI" 800 SRLI_INPUTS)
EOF

  write_file "$OUTDIR/sra_test.S" <<EOF
$(gen_shift_rtype_file "sra" "SRA" 900 SRA_INPUTS)
EOF

  write_file "$OUTDIR/srai_test.S" <<EOF
$(gen_shift_itype_file "srai" "SRAI" 1000 SRAI_INPUTS)
EOF

  write_file "$OUTDIR/sltu_test.S" <<EOF
$(gen_sltu_file "sltu" "SLTU" 1100 SLTU_INPUTS)
EOF

  write_file "$OUTDIR/sltiu_test.S" <<EOF
$(gen_sltiu_file "sltiu" "SLTIU" 1200 SLTIU_INPUTS)
EOF


  write_file "$OUTDIR/lb_test.S" <<EOF
$(gen_load_file "lb" "LB" 1300 LB_OFFSETS test_mem "$LOAD_MEM_HEX")
EOF

  write_file "$OUTDIR/lbu_test.S" <<EOF
$(gen_load_file "lbu" "LBU" 1400 LBU_OFFSETS test_mem "$LOAD_MEM_HEX")
EOF

  write_file "$OUTDIR/lh_test.S" <<EOF
$(gen_load_file "lh" "LH" 1500 LH_OFFSETS test_mem "$LOAD_MEM_HEX")
EOF

  write_file "$OUTDIR/lhu_test.S" <<EOF
$(gen_load_file "lhu" "LHU" 1600 LHU_OFFSETS test_mem "$LOAD_MEM_HEX")
EOF

  write_file "$OUTDIR/sb_test.S" <<EOF
$(gen_store_file "sb" "SB" 1700 SB_VECTORS)
EOF

  write_file "$OUTDIR/sh_test.S" <<EOF
$(gen_store_file "sh" "SH" 1800 SH_VECTORS)
EOF

  write_file "$OUTDIR/bne_test.S" <<EOF
$(gen_branch_file "bne" "BNE" 1900 BNE_INPUTS)
EOF

  write_file "$OUTDIR/blt_test.S" <<EOF
$(gen_branch_file "blt" "BLT" 2000 BLT_INPUTS)
EOF

  write_file "$OUTDIR/bltu_test.S" <<EOF
$(gen_branch_file "bltu" "BLTU" 2100 BLTU_INPUTS)
EOF

  write_file "$OUTDIR/bge_test.S" <<EOF
$(gen_branch_file "bge" "BGE" 2200 BGE_INPUTS)
EOF

  write_file "$OUTDIR/bgeu_test.S" <<EOF
$(gen_branch_file "bgeu" "BGEU" 2300 BGEU_INPUTS)
EOF

  write_file "$OUTDIR/jalr_test.S" <<EOF
$(gen_jalr_file 2400)
EOF

  write_file "$OUTDIR/lui_test.S" <<EOF
$(gen_lui_file "lui" "LUI" 2500 LUI_IMM20S)
EOF

  write_file "$OUTDIR/auipc_test.S" <<EOF
$(gen_auipc_file "auipc" "AUIPC" 2600 AUIPC_IMM20S)
EOF

}

main "$@"
