#!/usr/bin/env bash
set -euo pipefail

# Usage:
#   ./gen_pipeline_tests.sh [OUTDIR]
#   FORCE=1 ./gen_pipeline_tests.sh [OUTDIR]
#
# Generates two categories of pipeline tests targeting riscvpipe:
#   1. Hazard-safe (NOP-padded) — validates pipeline structure, no hazard unit needed
#   2. Hazard-specific — requires forwarding/stall/flush to produce correct results
#
# Pipeline context (riscvpipe):
#   - 5-stage: IF -> ID -> EX -> MEM -> WB
#   - Branches resolved in EX (2-cycle flush penalty on taken)
#   - Load-use stall: 1-cycle bubble injected via FlushE
#   - Forwarding: EX gets MEM result (ForwardAE/BE=10) or WB result (ForwardAE/BE=01)
#   - PCSrcE = (BranchE & BranchOpE) | JumpE flushes IF/ID and ID/EX
#
# Christian LamAlvarez
# clamalvarez@hmc.edu

OUTDIR="${1:-./pipeline_tests}"
FORCE="${FORCE:-0}"

mkdir -p "$OUTDIR"

# ============================================================
# UTILITIES
# ============================================================

die()        { echo "error: $*" >&2; exit 1; }

write_file() {
  local path="$1"
  local tmp="${path}.tmp"
  cat > "$tmp"
  if [[ -f "$path" ]] && cmp -s "$path" "$tmp"; then
    rm "$tmp";  echo "unchanged: $path"
  else
    mv "$tmp" "$path"; echo "updated:   $path"
  fi
}

emit_autogen_banner() {
  cat <<'EOF'
// AUTO-GENERATED FILE — DO NOT EDIT BY HAND
// Generated by gen_pipeline_tests.sh
// Christian LamAlvarez
// clamalvarez@hmc.edu

EOF
}

emit_header() {
  local testname="$1"
  emit_autogen_banner
  cat <<EOF
.extern return_${testname}_test
.extern fail

.section .text.init
.globl ${testname}_test
.type  ${testname}_test, @function

${testname}_test:
EOF
}

# RV32I canonical NOP = addi x0, x0, 0
# n=3 clears the full pipeline between a write and a dependent read
emit_nops() {
  local n="$1"
  for _ in $(seq 1 "$n"); do
    echo "        addi x0, x0, 0"
  done
}

emit_fail_footer() {
  local upper="$1" base_gp="$2"
  for i in $(seq 1 10); do
    local code=$((base_gp + i))
    cat <<EOF

Fail_${upper}_${i}:
        addi gp, x0, ${code}
        jal  x0, fail
EOF
  done
}

fits_imm12() { [[ "$1" -ge -2048 && "$1" -le 2047 ]]; }

# Load a 32-bit signed constant into rd.
# Uses addi if it fits, otherwise lui+addi.
emit_load_const() {
  local rd="$1" val="$2"
  read -r val_s val_hex < <(python3 - "$val" <<'PY'
import sys
x = int(sys.argv[1], 0)
u = x & 0xFFFFFFFF
s = u if u < 0x80000000 else u - 0x100000000
print(s, f"0x{u:08x}")
PY
)
  if fits_imm12 "$val_s"; then
    echo "        addi ${rd}, x0, ${val_s}"
  else
    local u=$(( val_s & 0xffffffff ))
    local hi=$(( (u + 0x800) >> 12 ))
    local lo=$(( u - (hi << 12) ))
    fits_imm12 "$lo" || die "lo out of range in emit_load_const: $lo"
    cat <<EOF
        lui  ${rd}, ${hi}
        addi ${rd}, ${rd}, ${lo}
EOF
  fi
}

# Load expected value into t3 (same contract as gen_rv32_tests.sh)
emit_load_expected_into_t3() {
  local exp_s="$1" exp_hex="$2"
  emit_load_const t3 "$exp_s"
}

# ============================================================
# EXPECTED RESULT HELPERS  (reused from gen_rv32_tests.sh)
# ============================================================

rv32_expect_alu() {
  python3 - "$1" "$2" "$3" <<'PY'
import sys
op  = sys.argv[1]
a   = int(sys.argv[2], 0)
b   = int(sys.argv[3], 0)

def u32(x): return x & 0xFFFFFFFF
def s32(u):
    u &= 0xFFFFFFFF
    return u if u < 0x80000000 else u - 0x100000000

au, bu = u32(a), u32(b)
as_, bs_ = s32(au), s32(bu)

ops = {
  "add":  u32(au + bu),
  "sub":  u32(au - bu),
  "and":  u32(au & bu),
  "or":   u32(au | bu),
  "xor":  u32(au ^ bu),
  "slt":  1 if as_ < bs_ else 0,
  "sltu": 1 if au < bu  else 0,
  "sll":  u32(au << (bu & 0x1f)),
  "srl":  au >> (bu & 0x1f),
  "sra":  u32(as_ >> (bu & 0x1f)),
  "addi": u32(au + bu),
  "andi": u32(au & bu),
  "ori":  u32(au | bu),
  "xori": u32(au ^ bu),
  "slti": 1 if as_ < bs_ else 0,
  "mul":  u32(au * bu),
  "mulh": u32((as_ * bs_) >> 32),
  "mulhu":u32((au * bu)  >> 32),
  "mulhsu": u32((as_ * bu) >> 32),
}
res = ops[op]
res_u = u32(res)
res_s = s32(res_u)
print(res_s, f"0x{res_u:08x}")
PY
}

rv32_expect_branch() {
  python3 - "$1" "$2" "$3" <<'PY'
import sys
op, rs1, rs2 = sys.argv[1], int(sys.argv[2],0), int(sys.argv[3],0)
def u32(x): return x & 0xFFFFFFFF
def s32(u): u&=0xFFFFFFFF; return u if u<0x80000000 else u-0x100000000
au,bu=u32(rs1),u32(rs2); as_,bs_=s32(au),s32(bu)
r={"beq":au==bu,"bne":au!=bu,"blt":as_<bs_,"bge":as_>=bs_,
   "bltu":au<bu,"bgeu":au>=bu}[op]
print(1 if r else 0)
PY
}

# ============================================================
# CATEGORY 1 — HAZARD-SAFE (NOP-padded)
# 3 NOPs between every write and dependent read.
# Should pass on bare pipeline with no hazard unit.
# ============================================================

# Generic ALU block (R-type or I-type, two register operands)
# args: upper i op rs1_val rs2_val next
emit_nop_alu_block() {
  local upper="$1" i="$2" op="$3" rs1="$4" rs2="$5" next="$6"
  read -r exp_s exp_hex < <(rv32_expect_alu "$op" "$rs1" "$rs2")
  cat <<EOF
    test${i}:
EOF
  emit_load_const t0 "$rs1"
  emit_load_const t1 "$rs2"
  cat <<EOF
        ${op}  t2, t0, t1
EOF
  emit_nops 3
  emit_load_expected_into_t3 "$exp_s" "$exp_hex"
  cat <<EOF
        beq  t2, t3, ${next}
        jal  x0, Fail_${upper}_${i}

EOF
}

# NOP-padded load/store roundtrip block
# args: upper i store_val next
emit_nop_load_store_block() {
  local upper="$1" i="$2" val="$3" next="$4"
  read -r val_s _ < <(python3 - "$val" <<'PY'
import sys; x=int(sys.argv[1],0); u=x&0xFFFFFFFF
print(u if u<0x80000000 else u-0x100000000, f"0x{u:08x}")
PY
)
  cat <<EOF
    test${i}:
        addi sp, sp, -4
EOF
  emit_load_const t0 "$val_s"
  cat <<EOF
        sw   t0, 0(sp)
EOF
  emit_nops 3
  cat <<EOF
        lw   t2, 0(sp)
EOF
  emit_nops 3
  emit_load_expected_into_t3 "$val_s" ""
  cat <<EOF
        beq  t2, t3, ${next}
        jal  x0, Fail_${upper}_${i}
        addi sp, sp, 4

EOF
}

# NOP-padded branch block — branch is not taken (fall-through path verified)
# args: upper i op rs1 rs2 next
emit_nop_branch_block() {
  local upper="$1" i="$2" op="$3" rs1="$4" rs2="$5" next="$6"
  local exp; exp="$(rv32_expect_branch "$op" "$rs1" "$rs2")"
  cat <<EOF
    test${i}:
EOF
  emit_load_const t0 "$rs1"
  emit_load_const t1 "$rs2"
  cat <<EOF
        addi t2, x0, 0
        ${op}  t0, t1, ${upper}_TAKEN_${i}
        jal  x0, ${upper}_AFTER_${i}
${upper}_TAKEN_${i}:
        addi t2, x0, 1
${upper}_AFTER_${i}:
EOF
  emit_nops 3
  cat <<EOF
        addi t3, x0, ${exp}
        beq  t2, t3, ${next}
        jal  x0, Fail_${upper}_${i}

EOF
}

# NOP-padded multiply block
# args: upper i op rs1 rs2 next
emit_nop_mul_block() {
  local upper="$1" i="$2" op="$3" rs1="$4" rs2="$5" next="$6"
  read -r exp_s exp_hex < <(rv32_expect_alu "$op" "$rs1" "$rs2")
  cat <<EOF
    test${i}:
EOF
  emit_load_const t0 "$rs1"
  emit_load_const t1 "$rs2"
  cat <<EOF
        ${op}  t2, t0, t1
EOF
  emit_nops 3
  emit_load_expected_into_t3 "$exp_s" "$exp_hex"
  cat <<EOF
        beq  t2, t3, ${next}
        jal  x0, Fail_${upper}_${i}

EOF
}

# ============================================================
# CATEGORY 2 — HAZARD-SPECIFIC
# These tests ONLY produce correct results if the hazard unit
# is functioning correctly.
# ============================================================

# --- 2a. EX->EX forwarding (ForwardAE/BE = 2'b10) ---
# Producer is immediately followed by consumer.
# Without EX->EX forward, consumer reads stale register file value.
# args: upper i op rs1_val rs2_val next
emit_raw_ex_ex_block() {
  local upper="$1" i="$2" op="$3" rs1="$4" rs2="$5" next="$6"
  read -r exp_s exp_hex < <(rv32_expect_alu "add" "$rs1" "$rs2")
  cat <<EOF
    test${i}:
EOF
  emit_load_const t0 "$rs1"
  emit_nops 3                          # let t0 settle in WB first
  emit_load_const t1 "$rs2"
  emit_nops 3                          # let t1 settle in WB first
  # Now produce a new value in t0 — next instruction immediately consumes it
  emit_load_const t0 "$rs1"
  cat <<EOF
        add  t2, t0, t1                # EX->EX forward on t0 required
EOF
  emit_nops 3
  emit_load_expected_into_t3 "$exp_s" "$exp_hex"
  cat <<EOF
        beq  t2, t3, ${next}
        jal  x0, Fail_${upper}_${i}

EOF
}

# --- 2b. MEM->EX forwarding (ForwardAE/BE = 2'b01) ---
# One instruction separates producer from consumer.
# Without MEM->EX forward, consumer reads stale register file value.
# args: upper i rs1_val rs2_val next
emit_raw_mem_ex_block() {
  local upper="$1" i="$2" rs1="$3" rs2="$4" next="$5"
  read -r exp_s exp_hex < <(rv32_expect_alu "add" "$rs1" "$rs2")
  cat <<EOF
    test${i}:
EOF
  emit_load_const t1 "$rs2"
  emit_nops 3
  # Produce t0; one intervening real instruction before consumer
  emit_load_const t0 "$rs1"
  cat <<EOF
        addi x0, x0, 0                 # 1 intervening instr (not dependent)
        add  t2, t0, t1                # MEM->EX forward on t0 required
EOF
  emit_nops 3
  emit_load_expected_into_t3 "$exp_s" "$exp_hex"
  cat <<EOF
        beq  t2, t3, ${next}
        jal  x0, Fail_${upper}_${i}

EOF
}

# --- 2c. Load-use stall ---
# lw immediately followed by use of loaded register.
# Hazard unit must insert 1-cycle bubble (stall IF/ID, flush EX).
# Without stall, consumer reads old register file value instead of loaded data.
# args: upper i val next
emit_load_use_block() {
  local upper="$1" i="$2" val="$3" next="$4"
  read -r val_s _ < <(python3 - "$val" <<'PY'
import sys; x=int(sys.argv[1],0); u=x&0xFFFFFFFF
print(u if u<0x80000000 else u-0x100000000, f"0x{u:08x}")
PY
)
  cat <<EOF
    test${i}:
        addi sp, sp, -4
EOF
  emit_load_const t0 "$val_s"
  cat <<EOF
        sw   t0, 0(sp)
        lw   t1, 0(sp)                 # load
        add  t2, t1, x0               # immediate use — load-use stall required
EOF
  emit_nops 3
  emit_load_expected_into_t3 "$val_s" ""
  cat <<EOF
        beq  t2, t3, ${next}
        jal  x0, Fail_${upper}_${i}
        addi sp, sp, 4

EOF
}

# --- 2d. Control hazard — branch flush ---
# Always-taken branch; the two instructions fetched speculatively
# after the branch (in IF and ID when branch resolves in EX) must be
# flushed. Without flush, those instructions corrupt t3.
# Branch resolved in EX => 2-cycle penalty; 2 speculative fetches flushed.
# args: upper i next
emit_branch_flush_block() {
  local upper="$1" i="$2" next="$3"
  cat <<EOF
    test${i}:
        addi t3, x0, 0                # flag = 0
        addi t0, x0, 5
        addi t1, x0, 5
        beq  t0, t1, ${upper}_TAKEN_${i}  # always-taken (5==5)
        addi t3, x0, 99               # speculatively fetched — must be flushed
        addi t3, x0, 99               # speculatively fetched — must be flushed
${upper}_TAKEN_${i}:
        addi t4, x0, 0
        beq  t3, t4, ${next}          # t3 must still be 0
        jal  x0, Fail_${upper}_${i}

EOF
}

# --- 2e. WAW (Write-After-Write) ---
# Two consecutive writes to same register; second write must win.
# In-order pipeline: second write always arrives later so this
# should pass even without special WAW logic — useful sanity check.
# args: upper i val_a val_b next
emit_waw_block() {
  local upper="$1" i="$2" val_a="$3" val_b="$4" next="$5"
  read -r vb_s _ < <(python3 - "$val_b" <<'PY'
import sys; x=int(sys.argv[1],0); u=x&0xFFFFFFFF
print(u if u<0x80000000 else u-0x100000000, f"0x{u:08x}")
PY
)
  cat <<EOF
    test${i}:
EOF
  emit_load_const t2 "$val_a"
  emit_load_const t2 "$val_b"   # second write — must be the survivor
  emit_nops 3
  emit_load_expected_into_t3 "$vb_s" ""
  cat <<EOF
        beq  t2, t3, ${next}
        jal  x0, Fail_${upper}_${i}

EOF
}

# --- 2f. WAR (Write-After-Read) ---
# Instruction reads t0, then t0 is overwritten. The reading
# instruction must see the original value; the write must not
# corrupt the earlier read's result in t2.
# args: upper i orig_val new_val next
emit_war_block() {
  local upper="$1" i="$2" orig="$3" newval="$4" next="$5"
  read -r orig_s _ < <(python3 - "$orig" <<'PY'
import sys; x=int(sys.argv[1],0); u=x&0xFFFFFFFF
print(u if u<0x80000000 else u-0x100000000, f"0x{u:08x}")
PY
)
  cat <<EOF
    test${i}:
EOF
  emit_load_const t0 "$orig_s"
  emit_nops 3
  cat <<EOF
        add  t2, t0, x0              # read t0 into t2
EOF
  emit_load_const t0 "$newval"        # overwrite t0 — must not affect t2
  emit_nops 3
  emit_load_expected_into_t3 "$orig_s" ""
  cat <<EOF
        beq  t2, t3, ${next}         # t2 must still hold orig value
        jal  x0, Fail_${upper}_${i}

EOF
}

# ============================================================
# FILE GENERATORS
# ============================================================

gen_nop_alu_file() {
  local name="NOP_ALU" base_gp=100
  emit_header "nop_alu"
  local vectors=(
    "add  10  20"   "add  -1  1"    "sub  50  30"   "sub  -2048 1"
    "and  0xFF 0x0F" "or  0xF0 0x0F" "xor 0xAA 0x55" "slt  -1  0"
    "sltu 0  -1"    "add  2047 1"
  )
  local i=1
  for v in "${vectors[@]}"; do
    read -r op rs1 rs2 <<<"$v"
    local next="test$((i+1))"; [[ $i -eq 10 ]] && next="pass"
    emit_nop_alu_block "$name" "$i" "$op" "$rs1" "$rs2" "$next"
    i=$((i+1))
  done
  cat <<EOF
    pass:
        jal  x0, return_nop_alu_test
EOF
  emit_fail_footer "$name" "$base_gp"
}

gen_nop_load_store_file() {
  local name="NOP_LS" base_gp=200
  emit_header "nop_load_store"
  local vals=(0 1 -1 42 2147483647 -2147483648 255 -128 1000 -1000)
  local i=1
  for val in "${vals[@]}"; do
    local next="test$((i+1))"; [[ $i -eq 10 ]] && next="pass"
    emit_nop_load_store_block "$name" "$i" "$val" "$next"
    i=$((i+1))
  done
  cat <<EOF
    pass:
        jal  x0, return_nop_load_store_test
EOF
  emit_fail_footer "$name" "$base_gp"
}

gen_nop_branch_file() {
  local name="NOP_BR" base_gp=300
  emit_header "nop_branch"
  # mix of taken (1) and not-taken (0) cases across branch types
  local vectors=(
    "beq   5   5"   "beq   5   6"   "bne   1   2"   "bne   3   3"
    "blt  -1   0"   "blt   1  -1"   "bge   0  -1"   "bge  -1   0"
    "bltu  0  -1"   "bgeu -1   0"
  )
  local i=1
  for v in "${vectors[@]}"; do
    read -r op rs1 rs2 <<<"$v"
    local next="test$((i+1))"; [[ $i -eq 10 ]] && next="pass"
    emit_nop_branch_block "$name" "$i" "$op" "$rs1" "$rs2" "$next"
    i=$((i+1))
  done
  cat <<EOF
    pass:
        jal  x0, return_nop_branch_test
EOF
  emit_fail_footer "$name" "$base_gp"
}

gen_nop_mul_file() {
  local name="NOP_MUL" base_gp=400
  emit_header "nop_mul"
  local vectors=(
    "mul      6       7"
    "mul     -1       1"
    "mul      0    1000"
    "mul  -2048    2047"
    "mulh     -1      -1"
    "mulh  2147483647 2"
    "mulhu    -1      -1"
    "mulhu     0      -1"
    "mulhsu   -1      -1"
    "mulhsu    1      -1"
  )
  local i=1
  for v in "${vectors[@]}"; do
    read -r op rs1 rs2 <<<"$v"
    local next="test$((i+1))"; [[ $i -eq 10 ]] && next="pass"
    emit_nop_mul_block "$name" "$i" "$op" "$rs1" "$rs2" "$next"
    i=$((i+1))
  done
  cat <<EOF
    pass:
        jal  x0, return_nop_mul_test
EOF
  emit_fail_footer "$name" "$base_gp"
}

gen_raw_ex_ex_file() {
  local name="RAW_EX_EX" base_gp=500
  emit_header "raw_ex_ex"
  local vectors=(
    "10 20"  "-1 1"   "0 0"    "100 -100"  "2047 1"
    "-2048 -1" "1 -1" "42 42"  "255 1"     "-128 -1"
  )
  local i=1
  for v in "${vectors[@]}"; do
    read -r rs1 rs2 <<<"$v"
    local next="test$((i+1))"; [[ $i -eq 10 ]] && next="pass"
    emit_raw_ex_ex_block "$name" "$i" "add" "$rs1" "$rs2" "$next"
    i=$((i+1))
  done
  cat <<EOF
    pass:
        jal  x0, return_raw_ex_ex_test
EOF
  emit_fail_footer "$name" "$base_gp"
}

gen_raw_mem_ex_file() {
  local name="RAW_MEM_EX" base_gp=600
  emit_header "raw_mem_ex"
  local vectors=(
    "10 20"  "-1 1"   "0 5"    "100 -100"  "2047 0"
    "-2048 2048" "1 -1" "42 0" "255 -1"    "-128 128"
  )
  local i=1
  for v in "${vectors[@]}"; do
    read -r rs1 rs2 <<<"$v"
    local next="test$((i+1))"; [[ $i -eq 10 ]] && next="pass"
    emit_raw_mem_ex_block "$name" "$i" "$rs1" "$rs2" "$next"
    i=$((i+1))
  done
  cat <<EOF
    pass:
        jal  x0, return_raw_mem_ex_test
EOF
  emit_fail_footer "$name" "$base_gp"
}

gen_load_use_file() {
  local name="LOAD_USE" base_gp=700
  emit_header "load_use"
  local vals=(0 1 -1 42 100 -100 2047 -2048 255 -128)
  local i=1
  for val in "${vals[@]}"; do
    local next="test$((i+1))"; [[ $i -eq 10 ]] && next="pass"
    emit_load_use_block "$name" "$i" "$val" "$next"
    i=$((i+1))
  done
  cat <<EOF
    pass:
        jal  x0, return_load_use_test
EOF
  emit_fail_footer "$name" "$base_gp"
}

gen_branch_flush_file() {
  local name="BR_FLUSH" base_gp=800
  emit_header "branch_flush"
  local i=1
  for i in $(seq 1 10); do
    local next="test$((i+1))"; [[ $i -eq 10 ]] && next="pass"
    emit_branch_flush_block "$name" "$i" "$next"
  done
  cat <<EOF
    pass:
        jal  x0, return_branch_flush_test
EOF
  emit_fail_footer "$name" "$base_gp"
}

gen_waw_war_file() {
  local name="WAW_WAR" base_gp=900
  emit_header "waw_war"
  # 5 WAW blocks then 5 WAR blocks
  local waw_vectors=("1 2" "-1 0" "100 200" "2047 -2048" "0 1")
  local war_vectors=("10 99" "-1 42" "0 1" "2047 -1" "-2048 2048")
  local i=1
  for v in "${waw_vectors[@]}"; do
    read -r va vb <<<"$v"
    local next="test$((i+1))"
    emit_waw_block "$name" "$i" "$va" "$vb" "$next"
    i=$((i+1))
  done
  for v in "${war_vectors[@]}"; do
    read -r orig newval <<<"$v"
    local next="test$((i+1))"; [[ $i -eq 10 ]] && next="pass"
    emit_war_block "$name" "$i" "$orig" "$newval" "$next"
    i=$((i+1))
  done
  cat <<EOF
    pass:
        jal  x0, return_waw_war_test
EOF
  emit_fail_footer "$name" "$base_gp"
}

# ============================================================
# MAIN
# ============================================================

main() {
  # --- Category 1: Hazard-safe NOP-padded ---
  write_file "$OUTDIR/nop_alu_test.S"        < <(gen_nop_alu_file)
  write_file "$OUTDIR/nop_load_store_test.S" < <(gen_nop_load_store_file)
  write_file "$OUTDIR/nop_branch_test.S"     < <(gen_nop_branch_file)
  write_file "$OUTDIR/nop_mul_test.S"        < <(gen_nop_mul_file)

  # --- Category 2: Hazard-specific ---
  write_file "$OUTDIR/raw_ex_ex_test.S"      < <(gen_raw_ex_ex_file)
  write_file "$OUTDIR/raw_mem_ex_test.S"     < <(gen_raw_mem_ex_file)
  write_file "$OUTDIR/load_use_test.S"       < <(gen_load_use_file)
  write_file "$OUTDIR/branch_flush_test.S"   < <(gen_branch_flush_file)
  write_file "$OUTDIR/waw_war_test.S"        < <(gen_waw_war_file)

  echo ""
  echo "Done. Generated tests in $OUTDIR:"
  echo "  Category 1 (hazard-safe):   nop_alu, nop_load_store, nop_branch, nop_mul"
  echo "  Category 2 (hazard-specific): raw_ex_ex, raw_mem_ex, load_use, branch_flush, waw_war"
}

main "$@"
